### ISSUE TITLE
Full Node Articles Only Displaying Teaser

### ISSUE THREAD

**Issue by penguininja** [ryanaslett/bitchmedia#33]
Full node display of articles are only displaying teasers since the last big code push. Not sure what could be causing this. Thoughts?

![teaser](https://cloud.githubusercontent.com/assets/430102/5417112/063847d6-81eb-11e4-9952-2b2e6d3192d7.png)

**Comment by penguininja** [comment]
Adding this to the high priority milestones. Any ideas on this?

**Comment by ryanaslett** [comment]
Yep, I think that the "Use custom display settings" got turned on for full content, which then inherited all the teaser settings. I've switched it back.

**Comment by ryanaslett** [comment]
Let me know if this needs anything else

**Comment by penguininja** [comment]
Looks good, thanks!
